version: 0.0
os: linux
hooks:
  BeforeInstall:
    - location: script/install_dependencies
      timeout: 300
      runas: root
    - location: script/start_server
      timeout: 300
      runas: root
  
